import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import Button from "~/components/Button";
import TextInput from "~/components/TextInput";

const Home: NextPage = () => {
  const [urls, setUrls] = useState({
    url1: "",
    url2: "",
  });

  const { url1, url2 } = urls;

  const router = useRouter();

  const urlRegex =
    /^https?:\/\/(?:(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/=]*)|(?:localhost:\d{1,5}(?:\/|$)))$/;

  const areUrlsValid = Object.entries(urls)
    .map(([key, value]) => urlRegex.test(value))
    .every((isValid) => isValid);

  function handleChange(e: any) {
    const { name, value } = e.target;
    setUrls((prev) => ({
      ...prev,
      [name]: value,
    }));
  }

  function handleSubmit(e: any) {
    e.preventDefault();
    if (url1 && url2) {
      router.push(
        `/compare?url1=${encodeURIComponent(url1)}&url2=${encodeURIComponent(
          url2
        )}`
      );
    }
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full items-center justify-center bg-zinc-900">
        <section className="m-4 w-full max-w-md rounded-xl bg-zinc-100 p-7 shadow-xl shadow-[#040404]">
          <header className="mb-6 text-center">
            <h1 className="text-2xl font-medium">Overlay websites</h1>
          </header>
          <form className="space-y-6" onSubmit={handleSubmit}>
            <div>
              <TextInput
                icon={"/globe.svg"}
                placeholder={"Enter url1..."}
                name={"url1"}
                value={url1}
                onChange={handleChange}
              />
            </div>
            <div>
              <TextInput
                icon={"/globe.svg"}
                placeholder={"Enter url2..."}
                name={"url2"}
                value={url2}
                onChange={handleChange}
              />
            </div>
            <div className="[&_button]:w-full">
              <Button
                variant={areUrlsValid ? "primary" : "outline"}
                disabled={!areUrlsValid}
              >
                <span>Start</span>
              </Button>
            </div>
          </form>
        </section>
      </main>
    </>
  );
};

export default Home;
